### ISSUE TITLE
ConfigurationExtensions.kt should have configuration for `api` config

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#423]
The `java-library` plugin exposes several new configurations:
https://docs.gradle.org/current/userguide/java_library_plugin.html

Currently, the `apiElements` configuration is exposed in the `ConfigurationExtensions.kt` file but not the `api` configuration.

**Comment by mkobit** [comment]
I believe this is fixed in `0.10.1` (https://github.com/gradle/kotlin-dsl/releases/tag/v0.10.1) and will be in Gradle 4.1 . Also see https://github.com/gradle/kotlin-dsl/issues/337

**Comment by eskatos** [comment]
@JLLeitschuh, @mkobit is right, #337 removed all hardcoded extensions for configurations in favor of dynamically generated accessors for configurations contributed by plugins. This will ship with Gradle 4.1.

Closing

**Comment by felipecsl** [comment]
I'm confused as I still don't set `api` available, tried with Gradle 4.5.1
Also tried `apiElements` but that didn't seem to work either.

**Comment by awesometown** [comment]
I was confused as well and had trouble finding a good example, but this seems to work:

```
plugins {
    `java-library`
}

dependencies {
    api("dependency:whatever:etc")
}
```

I gather prior to #337, `implementation`, `apiElement` etc. worked regardless of whether you used the `java-library` plugin because there was hard-coded support for them. After #337, configurations (like `api`) are dynamically created based on which plugins are applied, but this means that you have to actually apply the `java-library` plugin (which I hadn't been doing).
