### ISSUE TITLE
KT-20167: Kotlin DSL project won't build under JDK 9

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#454]
The oracle JDK 9 is due to be released September 23. Many more developers will have JDK 9 on their systems. As such, the Kotlin DSL needs to be able to support being built and tested under JDK 9.

### Expected Behavior

I would expect the ability to build and test the Kotlin DSL build to succeed under JDK 9.

### Current Behavior

Currently, in my testing on Travis CI the build fails:
https://travis-ci.org/JLLeitschuh/kotlin-dsl/jobs/262691730#L487-L490

<details>
<summary>Very long log</summary>
<pre>
$ javac -J-Xmx32m -version
javac 9
107.95s$ ./gradlew assemble
Downloading https://repo.gradle.org/gradle/dist-snapshots/gradle-kotlin-dsl-4.1-20170728152452+0000-all.zip
......................................................................................
Unzipping /home/travis/.gradle/wrapper/dists/gradle-kotlin-dsl-4.1-20170728152452+0000-all/e0n85zynz8q7sl3rcq4r5ltay/gradle-kotlin-dsl-4.1-20170728152452+0000-all.zip to /home/travis/.gradle/wrapper/dists/gradle-kotlin-dsl-4.1-20170728152452+0000-all/e0n85zynz8q7sl3rcq4r5ltay
Set executable permissions for: /home/travis/.gradle/wrapper/dists/gradle-kotlin-dsl-4.1-20170728152452+0000-all/e0n85zynz8q7sl3rcq4r5ltay/gradle-4.1-20170728152452+0000/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Generating JAR file 'gradle-api-4.1-20170728152452+0000.jar'
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin/1.1.3-2/kotlin-gradle-plugin-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-annotation-processing/1.1.3-2/kotlin-annotation-processing-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-project/1.1.3-2/kotlin-project-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-stdlib/1.1.3-2/kotlin-stdlib-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/commons-io/commons-io/2.4/commons-io-2.4.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.3-2/kotlin-compiler-embeddable-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-android-extensions/1.1.3-2/kotlin-android-extensions-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-runner/1.1.3-2/kotlin-compiler-runner-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/commons-lang/commons-lang/2.4/commons-lang-2.4.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.1.3-2/kotlin-gradle-plugin-api-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/apache/commons/commons-parent/9/commons-parent-9.pom
Download https://repo.gradle.org/gradle/repo/org/apache/commons/commons-parent/25/commons-parent-25.pom
Download https://repo.gradle.org/gradle/repo/org/apache/apache/4/apache-4.pom
Download https://repo.gradle.org/gradle/repo/org/apache/apache/9/apache-9.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/annotations/13.0/annotations-13.0.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-android-extensions/1.1.3-2/kotlin-android-extensions-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin/1.1.3-2/kotlin-gradle-plugin-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-stdlib/1.1.3-2/kotlin-stdlib-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/annotations/13.0/annotations-13.0.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.1.3-2/kotlin-gradle-plugin-api-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-runner/1.1.3-2/kotlin-compiler-runner-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-annotation-processing/1.1.3-2/kotlin-annotation-processing-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.3-2/kotlin-compiler-embeddable-1.1.3-2.jar
Generating JAR file 'gradle-test-kit-4.1-20170728152452+0000.jar'
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/ow2/asm/asm-all/5.1/asm-all-5.1.pom
Download https://repo.gradle.org/gradle/repo/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom
Download https://repo.gradle.org/gradle/repo/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://repo.gradle.org/gradle/repo/org/ow2/asm/asm-all/5.1/asm-all-5.1.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.jar
:buildSrc:clean
:buildSrc:compileKotlin
Using kotlin incremental compilation
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/travis/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.3-2/20bbabe4719a89eb83eca78dd74c606274f7f320/kotlin-compiler-embeddable-1.1.3-2.jar: Library has Kotlin runtime bundled into it
e: /home/travis/build/JLLeitschuh/kotlin-dsl/buildSrc/src/main/kotlin/integration/Benchmark.kt: (182, 19): Unresolved reference: bind
:buildSrc:compileKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Failed to notify build listener.
> java.lang.ExceptionInInitializerError (no error message)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 23s
The command "eval ./gradlew assemble " failed. Retrying, 2 of 3.
:buildSrc:clean
:buildSrc:compileKotlin
Using kotlin incremental compilation
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/travis/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.3-2/20bbabe4719a89eb83eca78dd74c606274f7f320/kotlin-compiler-embeddable-1.1.3-2.jar: Library has Kotlin runtime bundled into it
e: /home/travis/build/JLLeitschuh/kotlin-dsl/buildSrc/src/main/kotlin/integration/Benchmark.kt: (182, 19): Unresolved reference: bind
:buildSrc:compileKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Compilation error. See log for more details
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 9s
The command "eval ./gradlew assemble " failed. Retrying, 3 of 3.
:buildSrc:clean
:buildSrc:compileKotlin
Using kotlin incremental compilation
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/travis/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.3-2/20bbabe4719a89eb83eca78dd74c606274f7f320/kotlin-compiler-embeddable-1.1.3-2.jar: Library has Kotlin runtime bundled into it
e: /home/travis/build/JLLeitschuh/kotlin-dsl/buildSrc/src/main/kotlin/integration/Benchmark.kt: (182, 19): Unresolved reference: bind
:buildSrc:compileKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Compilation error. See log for more details
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 8s
The command "eval ./gradlew assemble " failed 3 times.
</pre>
</details>

### Context

This may be the reason that my [changes to the Junit 5 project don't work correctly](https://travis-ci.org/junit-team/junit5/jobs/262456240#L686).
I haven't worked enough with JDK 9 to try to fix this.

### Steps to Reproduce (for bugs)

Try to run the build with JDK 9.

### Your Environment

Whatever the `develop` branch is running.

### TL;DR

This bug has been narrowed down and captured here:
https://youtrack.jetbrains.com/issue/KT-20167

**Comment by JLLeitschuh** [comment]
Possibly related issue:
https://youtrack.jetbrains.com/issue/KT-19557

**Comment by JLLeitschuh** [comment]
https://travis-ci.org/JLLeitschuh/kotlin-dsl/jobs/262756429#L443-L652

<details>
<summary>New failure log after update</summary>
<code>
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
Patching redis-server init script
$ jdk_switcher use oraclejdk9
Switching to Oracle JDK9 (java-9-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-9-oracle
git.checkout
0.72s$ git clone --depth=50 --branch=task/travis-jdk9 https://github.com/JLLeitschuh/kotlin-dsl.git JLLeitschuh/kotlin-dsl
Cloning into 'JLLeitschuh/kotlin-dsl'...
remote: Counting objects: 1517, done.
remote: Compressing objects: 100% (647/647), done.
remote: Total 1517 (delta 538), reused 1239 (delta 423), pack-reused 0
Receiving objects: 100% (1517/1517), 428.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (538/538), done.
$ cd JLLeitschuh/kotlin-dsl
$ git checkout -qf 7d55be788bdde5cb9ecd3087ba6bdd386b2a1877
$ export TERM=dumb
cache.1
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.12s$ Installing caching utilities
0.03s
2.69sattempting to download cache archive
fetching tasktravis-jdk9/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--jdk-oraclejdk9.tgz
fetching tasktravis-jdk9/cache--jdk-oraclejdk9.tgz
fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--jdk-oraclejdk9.tgz
fetching master/cache--jdk-oraclejdk9.tgz
could not download cache
0.03s
2.21sadding /home/travis/.gradle/caches to cache
creating directory /home/travis/.gradle/caches
adding /home/travis/.gradle/wrapper to cache
creating directory /home/travis/.gradle/wrapper
$ java -Xmx32m -version
java version "9"
Java(TM) SE Runtime Environment (build 9+175)
Java HotSpot(TM) 64-Bit Server VM (build 9+175, mixed mode)
$ javac -J-Xmx32m -version
javac 9
133.18s$ ./gradlew assemble
......................................................................................
Unzipping /home/travis/.gradle/wrapper/dists/gradle-kotlin-dsl-4.1-20170728152452+0000-all/e0n85zynz8q7sl3rcq4r5ltay/gradle-kotlin-dsl-4.1-20170728152452+0000-all.zip to /home/travis/.gradle/wrapper/dists/gradle-kotlin-dsl-4.1-20170728152452+0000-all/e0n85zynz8q7sl3rcq4r5ltay
Set executable permissions for: /home/travis/.gradle/wrapper/dists/gradle-kotlin-dsl-4.1-20170728152452+0000-all/e0n85zynz8q7sl3rcq4r5ltay/gradle-4.1-20170728152452+0000/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Generating JAR file 'gradle-api-4.1-20170728152452+0000.jar'
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin/1.1.3-2/kotlin-gradle-plugin-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-stdlib/1.1.3-2/kotlin-stdlib-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.3-2/kotlin-compiler-embeddable-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-annotation-processing/1.1.3-2/kotlin-annotation-processing-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.1.3-2/kotlin-gradle-plugin-api-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-runner/1.1.3-2/kotlin-compiler-runner-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-android-extensions/1.1.3-2/kotlin-android-extensions-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/commons-io/commons-io/2.4/commons-io-2.4.pom
Download https://repo.gradle.org/gradle/repo/commons-lang/commons-lang/2.4/commons-lang-2.4.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-project/1.1.3-2/kotlin-project-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/apache/commons/commons-parent/25/commons-parent-25.pom
Download https://repo.gradle.org/gradle/repo/org/apache/commons/commons-parent/9/commons-parent-9.pom
Download https://repo.gradle.org/gradle/repo/org/apache/apache/9/apache-9.pom
Download https://repo.gradle.org/gradle/repo/org/apache/apache/4/apache-4.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/annotations/13.0/annotations-13.0.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.1.3-2/kotlin-gradle-plugin-api-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-gradle-plugin/1.1.3-2/kotlin-gradle-plugin-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-android-extensions/1.1.3-2/kotlin-android-extensions-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-annotation-processing/1.1.3-2/kotlin-annotation-processing-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.3-2/kotlin-compiler-embeddable-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-stdlib/1.1.3-2/kotlin-stdlib-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://repo.gradle.org/gradle/repo/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/annotations/13.0/annotations-13.0.jar
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-compiler-runner/1.1.3-2/kotlin-compiler-runner-1.1.3-2.jar
Generating JAR file 'gradle-test-kit-4.1-20170728152452+0000.jar'
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.pom
Download https://repo.gradle.org/gradle/repo/org/ow2/asm/asm-all/5.1/asm-all-5.1.pom
Download https://repo.gradle.org/gradle/repo/org/ow2/asm/asm-parent/5.1/asm-parent-5.1.pom
Download https://repo.gradle.org/gradle/repo/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://repo.gradle.org/gradle/repo/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.jar
Download https://repo.gradle.org/gradle/repo/org/ow2/asm/asm-all/5.1/asm-all-5.1.jar
:buildSrc:clean
:buildSrc:compileKotlin
Using kotlin incremental compilation
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/travis/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.3-2/20bbabe4719a89eb83eca78dd74c606274f7f320/kotlin-compiler-embeddable-1.1.3-2.jar: Library has Kotlin runtime bundled into it
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy NO-SOURCE
:buildSrc:copyMainKotlinClasses
:buildSrc:processResources NO-SOURCE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestKotlin NO-SOURCE
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:copyTestKotlinClasses
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test NO-SOURCE
:buildSrc:check UP-TO-DATE
:buildSrc:build
FAILURE: Build failed with an exception.
* What went wrong:
Failed to notify build listener.
> Could not initialize class org.apache.commons.lang.SystemUtils
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 21s
The command "eval ./gradlew assemble " failed. Retrying, 2 of 3.
:buildSrc:clean
:buildSrc:compileKotlin
Using kotlin incremental compilation
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/travis/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.3-2/20bbabe4719a89eb83eca78dd74c606274f7f320/kotlin-compiler-embeddable-1.1.3-2.jar: Library has Kotlin runtime bundled into it
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/travis/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.3-2/20bbabe4719a89eb83eca78dd74c606274f7f320/kotlin-compiler-embeddable-1.1.3-2.jar: Library has Kotlin runtime bundled into it
Compilation with Kotlin compile daemon was not successful
java.lang.Exception: Error occurred in server thread; nested exception is: 
	java.lang.NoClassDefFoundError: com/sun/xml/internal/messaging/saaj/util/ByteOutputStream
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:60)
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:59)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemon(GradleKotlinCompilerRunner.kt:204)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemonOrFallback(GradleKotlinCompilerRunner.kt:158)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemonOrFallback(GradleKotlinCompilerRunner.kt:55)
	at org.jetbrains.kotlin.compilerRunner.KotlinCompilerRunner.runCompiler(KotlinCompilerRunner.kt:127)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runJvmCompiler(GradleKotlinCompilerRunner.kt:109)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:264)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:168)
	at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1161)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
Could not connect to kotlin daemon. Using fallback strategy.
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=b9ac9ab8-6768-411b-909b-0aebc021227c.1, currentDir=/home/travis/build/JLLeitschuh/kotlin-dsl}
Attempting to read last messages from the daemon log...
Daemon pid: 3366
  log file: /home/travis/.gradle/daemon/4.1-20170728152452+0000/daemon-3366.out.log
----- Last  20 lines from daemon log file - daemon-3366.out.log -----
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1161)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
Could not connect to kotlin daemon. Using fallback strategy.
----- End of the daemon log -----
FAILURE: Build failed with an exception.
* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
The command "eval ./gradlew assemble " failed. Retrying, 3 of 3.
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
:buildSrc:clean
:buildSrc:compileKotlin
Using kotlin incremental compilation
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/travis/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.3-2/20bbabe4719a89eb83eca78dd74c606274f7f320/kotlin-compiler-embeddable-1.1.3-2.jar: Library has Kotlin runtime bundled into it
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy NO-SOURCE
:buildSrc:copyMainKotlinClasses
:buildSrc:processResources NO-SOURCE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestKotlin NO-SOURCE
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:copyTestKotlinClasses
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test NO-SOURCE
:buildSrc:check UP-TO-DATE
:buildSrc:build
FAILURE: Build failed with an exception.
* What went wrong:
Failed to notify build listener.
> Could not initialize class org.apache.commons.lang.SystemUtils
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 27s
The command "eval ./gradlew assemble " failed 3 times.
The command "./gradlew assemble" failed and exited with 1 during .
</code>
</details>

**Comment by eskatos** [comment]
[KT-14988](https://youtrack.jetbrains.com/issue/KT-14988) Support running the Kotlin compiler on Java 9

Marked as fixed in Kotlin 1.1.4.

So, blocked by #414

**Comment by bamboo** [comment]
Except we still don't have a good solution for:

```
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.1.4-eap-69'] was not found in any of the following sources:

    - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
    - Gradle Central Plugin Repository (plugin 'org.jetbrains.kotlin.jvm' has no version '1.1.4-eap-69' - see https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm for available versions)
```

I guess we'll have to wait for the official 1.1.4.

**Comment by JLLeitschuh** [comment]
I don't understand what the above problem is? What is that error and what is causing it?
Can't you just use the `buildscript` block as a development patch?

**Comment by bamboo** [comment]
We could but we would have to change every single sample and test that relies on `org.jetbrains.kotlin.jvm`. And then change them back after the final `1.1.4` is released. Not a good solution.

In the meantime you could merge the `kotlin-1.1.4` branch into your branch to see if at least `./gradlew assemble` is green.

**Comment by JLLeitschuh** [comment]
For those who end up needing to dive in and understand Java 9 modules
http://openjdk.java.net/projects/jigsaw/spec/sotms

**Comment by JLLeitschuh** [comment]
As JDK 9 will be released on September 23 should this be added as a requirement for 1.0 release?

**Comment by JLLeitschuh** [comment]
Okay, so I now have JDK 9 installed on my own machine for some other thing I was working on so I figured I'd give this a shot.

The problem that travis is having is different from the problem that I get.

<details>
<summary>Another very long error that seems to stem from the kotlin compiler</summary>
<pre>
jonathanleitschuh@jonathasmbpwork ~/p/g/kotlin-dsl> ./gradlew :provider:check --stacktrace --no-daemon -Dkotlin.compiler.execution.strategy=in-proces
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.2-20170830140852+0000/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
[buildinfo] Not using buildInfo properties file for this build.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.text.StringFactory (file:/Users/jonathanleitschuh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.4-3/15ddf7af18d9931317d118834d71de5ba67b8035/kotlin-compiler-embeddable-1.1.4-3.jar) to constructor java.lang.String(char[],boolean)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.text.StringFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
warning: the '-d' option with a directory destination is ignored because '-Xbuild-file' is specified

> Task :tooling-models:compileKotlin
Using kotlin incremental compilation

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.text.StringFactory (file:/Users/jonathanleitschuh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.4-3/15ddf7af18d9931317d118834d71de5ba67b8035/kotlin-compiler-embeddable-1.1.4-3.jar) to constructor java.lang.String(char[],boolean)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.text.StringFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :provider:compileKotlin
Using kotlin incremental compilation

warning: the '-d' option with a directory destination is ignored because '-Xbuild-file' is specified
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.text.StringFactory (file:/Users/jonathanleitschuh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.1.4-3/15ddf7af18d9931317d118834d71de5ba67b8035/kotlin-compiler-embeddable-1.1.4-3.jar) to constructor java.lang.String(char[],boolean)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.text.StringFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :tooling-builders:compileKotlin
Using kotlin incremental compilation

warning: the '-d' option with a directory destination is ignored because '-Xbuild-file' is specified

> Task :fixtures:plugin-compiled-against-kotlin-1.0:compileKotlin
e: java.lang.reflect.InaccessibleObjectException: Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @512060e3
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
        at org.jetbrains.kotlin.com.intellij.util.DebugReflectionUtil.getAllFields(DebugReflectionUtil.java:52)
        at org.jetbrains.kotlin.com.intellij.util.DebugReflectionUtil.processStronglyReferencedValues(DebugReflectionUtil.java:90)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.findReferencedPsi(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.access$000(CachedValueChecker.java:40)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:81)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.DebugReflectionUtil.processStronglyReferencedValues(DebugReflectionUtil.java:104)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.findReferencedPsi(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.access$000(CachedValueChecker.java:40)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:81)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.DebugReflectionUtil.processStronglyReferencedValues(DebugReflectionUtil.java:104)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.findReferencedPsi(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.access$000(CachedValueChecker.java:40)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:81)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.DebugReflectionUtil.processStronglyReferencedValues(DebugReflectionUtil.java:104)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.findReferencedPsi(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.access$000(CachedValueChecker.java:40)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:81)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.DebugReflectionUtil.processStronglyReferencedValues(DebugReflectionUtil.java:104)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.findReferencedPsi(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.access$000(CachedValueChecker.java:40)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:81)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker$1.process(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.DebugReflectionUtil.processStronglyReferencedValues(DebugReflectionUtil.java:104)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.findReferencedPsi(CachedValueChecker.java:78)
        at org.jetbrains.kotlin.com.intellij.util.CachedValueChecker.checkProvider(CachedValueChecker.java:52)
        at org.jetbrains.kotlin.com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:57)
        at org.jetbrains.kotlin.com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:133)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.ClassInnerStuffCache.getInnerClasses(ClassInnerStuffCache.java:82)
        at org.jetbrains.kotlin.com.intellij.psi.impl.compiled.ClsClassImpl.getInnerClasses(ClsClassImpl.java:184)
        at org.jetbrains.kotlin.load.java.structure.impl.JavaClassImpl.getInnerClasses(JavaClassImpl.java:47)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope$nestedClassIndex$1.invoke(LazyJavaClassMemberScope.kt:631)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope$nestedClassIndex$1.invoke(LazyJavaClassMemberScope.kt:65)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getClassNames(LazyJavaClassMemberScope.kt:678)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.computeDescriptors(LazyJavaScope.kt:302)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$allDescriptors$1.invoke(LazyJavaScope.kt:57)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$allDescriptors$1.invoke(LazyJavaScope.kt:51)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedDescriptors(LazyJavaScope.kt:292)
        at org.jetbrains.kotlin.resolve.DescriptorUtils.getAllDescriptors(DescriptorUtils.java:566)
        at org.jetbrains.kotlin.load.java.sam.SingleAbstractMethodUtils.getAbstractMembers(SingleAbstractMethodUtils.java:48)
        at org.jetbrains.kotlin.load.java.sam.SingleAbstractMethodUtils.getSingleAbstractMethodOrNull(SingleAbstractMethodUtils.java:104)
        at org.jetbrains.kotlin.load.java.sam.SamConversionResolverImpl.resolveFunctionTypeIfSamInterface(SamConversionResolverImpl.kt:48)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor$functionTypeForSamInterface$1.invoke(LazyJavaClassDescriptor.kt:116)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor$functionTypeForSamInterface$1.invoke(LazyJavaClassDescriptor.kt:48)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor.getFunctionTypeForSamInterface(LazyJavaClassDescriptor.kt:129)
        at org.jetbrains.kotlin.load.java.sam.SamConversionResolverImpl.resolveSamConstructor(SamConversionResolverImpl.kt:33)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageScope.computeNonDeclaredFunctions(LazyJavaPackageScope.kt:152)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:89)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:51)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedFunctions(LazyJavaScope.kt:216)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getContributedFunctions(JvmPackageScope.kt:65)
        at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedFunctions(ChainedMemberScope.kt:39)
        at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedFunctions(AbstractScopeAdapter.kt:37)
        at org.jetbrains.kotlin.resolve.QualifiedExpressionResolver.collectCandidateDescriptors(QualifiedExpressionResolver.kt:203)
        at org.jetbrains.kotlin.resolve.QualifiedExpressionResolver.processSingleImport(QualifiedExpressionResolver.kt:178)
        at org.jetbrains.kotlin.resolve.QualifiedExpressionResolver.processImportReference(QualifiedExpressionResolver.kt:154)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$importedScopesProvider$1.invoke(LazyImportScope.kt:88)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$importedScopesProvider$1.invoke(LazyImportScope.kt:75)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver.getImportScope(LazyImportScope.kt:165)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$selectSingleFromImports$1.invoke(LazyImportScope.kt:140)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$selectSingleFromImports$2.invoke(LazyImportScope.kt:146)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver$selectSingleFromImports$2.invoke(LazyImportScope.kt:75)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager.compute(LockBasedStorageManager.java:211)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportResolver.selectSingleFromImports(LazyImportScope.kt:146)
        at org.jetbrains.kotlin.resolve.lazy.LazyImportScope.getContributedClassifier(LazyImportScope.kt:194)
        at org.jetbrains.kotlin.resolve.scopes.utils.ScopeUtilsKt.findClassifier(ScopeUtils.kt:74)
        at org.jetbrains.kotlin.resolve.QualifiedExpressionResolver.resolveDescriptorForType(QualifiedExpressionResolver.kt:71)
        at org.jetbrains.kotlin.resolve.TypeResolver.resolveDescriptorForType(TypeResolver.kt:616)
        at org.jetbrains.kotlin.resolve.TypeResolver$resolveTypeElement$1.visitUserType(TypeResolver.kt:162)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitUserType(KtVisitorVoid.java:905)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitUserType(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtUserType.accept(KtUserType.java:42)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:58)
        at org.jetbrains.kotlin.resolve.TypeResolver.resolveTypeElement(TypeResolver.kt:160)
        at org.jetbrains.kotlin.resolve.TypeResolver.doResolvePossiblyBareType(TypeResolver.kt:117)
        at org.jetbrains.kotlin.resolve.TypeResolver.resolvePossiblyBareType(TypeResolver.kt:105)
        at org.jetbrains.kotlin.resolve.TypeResolver.resolveType(TypeResolver.kt:75)
        at org.jetbrains.kotlin.resolve.TypeResolver.resolveType(TypeResolver.kt:70)
        at org.jetbrains.kotlin.resolve.DescriptorResolver.resolveSuperTypeListEntries(DescriptorResolver.java:180)
        at org.jetbrains.kotlin.resolve.DescriptorResolver.resolveSupertypes(DescriptorResolver.java:110)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$LazyClassTypeConstructor.computeSupertypes(LazyClassDescriptor.java:600)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:35)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:22)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:23)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:22)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getSuperClassNotAny(DescriptorUtils.kt:114)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getAllSuperclassesWithoutAny(DescriptorUtils.kt:309)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:50)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:30)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:56)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:30)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:64)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:30)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForMemberDeclarationResolution(LazyClassDescriptor.java:352)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getScopeForMemberDeclarationResolution(LazyClassMemberScope.kt:100)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.doGetFunctions(AbstractLazyMemberScope.kt:78)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.access$doGetFunctions(AbstractLazyMemberScope.kt:41)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:51)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:41)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.getContributedFunctions(AbstractLazyMemberScope.kt:70)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getContributedFunctions(LazyClassMemberScope.kt:126)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$1.visitNamedFunction(LazyDeclarationResolver.java:167)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$1.visitNamedFunction(LazyDeclarationResolver.java:118)
        at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:48)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.java:118)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.java:113)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.createFunctionDescriptors(LazyTopDownAnalyzer.kt:221)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:179)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzerForTopLevel.analyzeDeclarations(LazyTopDownAnalyzerForTopLevel.java:74)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzerForTopLevel.analyzeFiles(LazyTopDownAnalyzerForTopLevel.java:66)
        at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:136)
        at org.jetbrains.kotlin.resolve.jvm.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegrationWithCustomContext(TopDownAnalyzerFacadeForJVM.kt:67)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.analyze(KotlinToJVMBytecodeCompiler.kt:365)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:104)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:358)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:131)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:186)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:198)
        at org.jetbrains.kotlin.gradle.tasks.TasksKt.compileJvmNotIncrementally(Tasks.kt:285)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:173)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:104)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:179)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:135)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:122)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fixtures:plugin-compiled-against-kotlin-1.0:compileKotlin'.
> Internal compiler error. See log for more details
</pre>
</details>

The problem that I'm getting now is much further in the build than where [Travis CI currently fails](https://travis-ci.org/gradle/kotlin-dsl/jobs/270117838#L508). This may be because I'm running a newer JDK than travis.

My JDK:
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
``` 

Travis JDK:
```
java version "9"
Java(TM) SE Runtime Environment (build 9+175)
Java HotSpot(TM) 64-Bit Server VM (build 9+175, mixed mode)
```

**Comment by JLLeitschuh** [comment]
Now I'm getting a bunch of test failures. Which is better than where we were at before.
I'll push my changes to the PR so you can see them.

**Comment by JLLeitschuh** [comment]
If I check out my branch fresh and try to run it on JDK 9 I get the following:
```
> Configure project :
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.gradle.api.Project, unresolved supertypes: Comparable<Project>
    class org.gradle.api.plugins.ExtensionAware, unresolved supertypes: Object
    class org.gradle.api.plugins.PluginAware, unresolved supertypes: Object
    class groovy.lang.Closure, unresolved supertypes: Cloneable, Runnable, Serializable
    class groovy.lang.GroovyObjectSupport, unresolved supertypes: Object
    class groovy.lang.GroovyObject, unresolved supertypes: Object
    class groovy.lang.GroovyCallable, unresolved supertypes: Callable<V>
    class org.gradle.api.Action, unresolved supertypes: Object
    class org.gradle.api.NamedDomainObjectFactory, unresolved supertypes: Object
    class org.gradle.api.initialization.dsl.ScriptHandler, unresolved supertypes: Object
    class org.gradle.api.plugins.ExtraPropertiesExtension, unresolved supertypes: Object
    class org.gradle.api.NamedDomainObjectList, unresolved supertypes: List<T>
    class org.gradle.api.DomainObjectCollection, unresolved supertypes: Collection<T>
    class org.gradle.util.Configurable, unresolved supertypes: Object
    class org.gradle.api.artifacts.dsl.DependencyHandler, unresolved supertypes: Object
```

I was only able to get further if I'd build the project with JDK 8 first then run it under JDK 9.

**Comment by JLLeitschuh** [comment]
Closed by #493 & #455
